### ISSUE TITLE
[CHORE] data format 수정

### ISSUE THREAD

**Issue by gyeongminK** [seohyun319/HanALL#38]
- [x] /todays: Array로 감싸지 말고 object만 넘겨주기 (현재: [{...}]) (변경: {...})
- [x] /spellings: 검색 결과 1개 / 유사 검색 결과 분리
result: [ detail:{...}, similar:[{...}, {...}, {...}] ]
- [x] /spacings: 메인페이지 최신순, 조회수순 네이밍 (["hits_order":[{...}, {...}, {...}}], "created_at_order":[{...}, {...}, {...}]])
- [x] /spellings: 메인페이지 최신순, 조회수순 네이밍 (["hits_order":[{...}, {...}, {...}}], "created_at_order":[{...}, {...}, {...}]])
- [x] 디테일 api 철자/띄어쓰기, /today 다 related에 id랑 같이 title 주기
- [x] /today에서 해당 id 주기

**Comment by seohyun319** [comment]
- /spellings/{id}, /spacings/{id}, /today의 `related`에 id와 함께 title도 보내주세요
    - `related: { _id: "", title: "" }`
- /today의 정보에 해당하는 id도 같이 보내주세요

**Comment by gyeongminK** [comment]
@seohyun319 word index 수정해서 related data 형식 변경했습니다!
